/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sonymobile_nfclock_NfcLockService */

#ifndef _Included_com_sonymobile_nfclock_NfcLockService
#define _Included_com_sonymobile_nfclock_NfcLockService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sonymobile_nfclock_NfcLockService
 * Method:    isUrgentNfcLockStatus
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_sonymobile_nfclock_NfcLockService_isUrgentNfcLockStatus
  (JNIEnv *, jclass);

/*
 * Class:     com_sonymobile_nfclock_NfcLockService
 * Method:    getAuthArray
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_com_sonymobile_nfclock_NfcLockService_getAuthArray
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_sonymobile_nfclock_NfcLockService
 * Method:    checkPassphrase
 * Signature: (Ljava/lang/Object;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_sonymobile_nfclock_NfcLockService_checkPassphrase
  (JNIEnv *, jclass, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
